# Flowbot Configuration

# Trading parameters
quantity:
  type: uniform
  min: 1.0
  max: 2.0

# Time between trades (seconds) - much slower now
interval:
  type: uniform
  min: 30
  max: 60

# Probability of buying vs selling (1.0 = 100% BUY, 0.0 = 100% SELL)
p_buy: 1.0

# Maximum spend per market (USDC)
max_spend_per_market: 5.0

# Price filtering - only trade on outcomes with prices in this range
min_price: 0.10
max_price: 0.90

# Manual approval mode
manual_approval: true

# Markets will be automatically discovered from Gamma API
# You can optionally specify markets here to override auto-discovery:
# markets:
#   - "token_id_1"
#   - "token_id_2"

# Market Maker Configuration
market_maker:
  # Order size per level in USDC
  order_size: 1.0
  
  # Target spread as decimal (0.02 = 2%)
  spread_target: 0.02
  
  # Maximum position per token in USDC
  max_position: 10.0
  
  # Number of price levels to quote on each side
  price_levels: 3
  
  # Time between order refreshes (seconds)
  refresh_interval: 30 